//
// Created by chahla on 05/11/2023.
//

#ifndef PROGRAMACION7NOV_EXCEPCIONESNOINTERCEPTADAS_H
#define PROGRAMACION7NOV_EXCEPCIONESNOINTERCEPTADAS_H


class ExcepcionesNoInterceptadas {

};


#endif //PROGRAMACION7NOV_EXCEPCIONESNOINTERCEPTADAS_H
